version: 0.2
phases:
  install:
    commands:
      - echo Installing app dependencies...
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.18.9/2020-11-02/bin/linux/amd64/kubectl   
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
      - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
      - source ~/.bashrc
      - echo 'Check kubectl version'
      - kubectl version --short --client
  pre_build:
    commands:
      - echo Logging in to Amazon EKS...
      - aws eks --region us-east-1 update-kubeconfig --name my-cluster
      - echo check config 
      - kubectl config view --minify
      - echo check kubectl access
      - kubectl get svc
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
  #    - docker build --no-cache -t wordpress-web -f dockerfile .
      - docker-compose up -d
      - docker tag wordpress:latest 058750364011.dkr.ecr.us-east-1.amazonaws.com/wordpress:wordpress
      - docker tag mysql:8.0 058750364011.dkr.ecr.us-east-1.amazonaws.com/wordpress:mysql
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 058750364011.dkr.ecr.us-east-1.amazonaws.com/wordpress:wordpress
      - docker push 058750364011.dkr.ecr.us-east-1.amazonaws.com/wordpress:mysql
      - kubectl apply -f eks/deployment.yml
      - kubectl rollout restart -f eks/deployment.yml
      
