version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
  #    - docker build --no-cache -t wordpress-web -f dockerfile .
      - docker-compose up -d
      - docker tag wordpress public.ecr.aws/r2k1r7j6/final:wordpress
      - docker tag mysql:8.0 public.ecr.aws/r2k1r7j6/final:mysql
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/r2k1r7j6/final:wordpress
      - docker push public.ecr.aws/r2k1r7j6/final:mysql
