---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-demo
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 058750364011.dkr.ecr.us-east-1.amazonaws.com/wordpress:wordpress
          ports:
            - containerPort: 80
